version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "30494:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/app/frontend
    networks:
      - nyxusd-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    depends_on:
      - redis
    networks:
      - nyxusd-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nyxusd-network

networks:
  nyxusd-network:
    driver: bridge

volumes:
  redis_data:
