#!/bin/bash

echo "==================================="
echo "NYXUSD Vercel Environment Setup"
echo "==================================="
echo ""
echo "To fix the production issues on nyxusd.com, you need to set the following environment variables in Vercel:"
echo ""
echo "1. Go to: https://vercel.com/dashboard"
echo "2. Select your NYXUSD project"
echo "3. Go to Settings → Environment Variables"
echo "4. Add the following variables:"
echo ""
echo "REQUIRED VARIABLES:"
echo "==================="
echo ""
echo "OPENROUTER_API_KEY"
echo "  Value: [Your OpenRouter API key from https://openrouter.ai]"
echo "  Description: Required for AI functionality (backend only)"
echo ""
echo "APP_NAME"
echo "  Value: NyxUSD"
echo "  Description: Application name"
echo ""
echo "APP_URL"
echo "  Value: https://nyxusd.com"
echo "  Description: Production URL"
echo ""
echo "USE_MOCK_AI"
echo "  Value: false"
echo "  Description: Disable mock AI in production"
echo ""
echo "OPTIONAL BUT RECOMMENDED:"
echo "========================="
echo ""
echo "VITE_WALLETCONNECT_PROJECT_ID"
echo "  Value: [Your WalletConnect project ID]"
echo "  Description: Required for wallet connections"
echo "  Get from: https://cloud.walletconnect.com"
echo ""
echo "After adding these variables:"
echo "1. Click 'Save'"
echo "2. Redeploy your project (Vercel will prompt you)"
echo "3. Wait for deployment to complete"
echo "4. Test at https://nyxusd.com"
echo ""
echo "==================================="
echo "Local Testing"
echo "==================================="
echo ""
echo "To test locally with your API key:"
echo "1. Copy .env.example to .env"
echo "2. Add your OPENROUTER_API_KEY to .env (backend)"
echo "3. Run: cd frontend && npm run dev"
echo ""